"""Add OTP fields and telegram_id to users

Revision ID: 20d9013b090c
Revises: 0898da381eb8
Create Date: 2025-09-27 17:11:27.350302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d9013b090c'
down_revision: Union[str, None] = '0898da381eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_otp_request', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_request_count', sa.Integer(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'otp_request_count')
    op.drop_column('users', 'last_otp_request')
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'otp_expires')
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
