"""init_models_fixed

Revision ID: a6c0ed7c96b7
Revises: 
Create Date: 2025-08-25 23:12:15.418986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c0ed7c96b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_history', 'tracking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('price_history', 'wb_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('price_history', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('price_history', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('trackings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trackings', 'wb_item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('trackings', 'custom_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('trackings', 'min_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.drop_index('idx_trackings_wb_item_id', table_name='trackings')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_trackings_wb_item_id', 'trackings', ['wb_item_id'], unique=False)
    op.alter_column('trackings', 'min_rating',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('trackings', 'custom_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trackings', 'wb_item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('trackings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('price_history', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('price_history', 'rating',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('price_history', 'wb_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('price_history', 'tracking_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
